### ISSUE TITLE
UPDATE on npm

### ISSUE THREAD

**Issue by ronal2do** [graphql-community/create-graphql#101]
Please public a version 1.2.2 on [npm](https://www.npmjs.com/package/create-graphql) is 1.1.17 version

**Comment by davidrossjones** [comment]
Any update on this? Is this project still actively maintained?

**Comment by lucasbento** [comment]
`create-graphql` version on npm doesn't matter much, what actually counts is [generator-graphql](https://www.npmjs.com/package/generator-graphql) version.

Sometimes a release can only count with changes to generator as is the case of [1.2.2](https://github.com/graphql-community/create-graphql/releases/tag/v1.2.2).

You can see the last versions in [create-graphql](https://github.com/graphql-community/create-graphql/blob/master/packages/create-graphql/package.json#L4) and [generator-graphql](https://github.com/graphql-community/create-graphql/blob/master/packages/generator/package.json#L4) `package.json`.
